### ISSUE TITLE
Getting the docuemnt's id (something unique)

### ISSUE THREAD

**Issue by softmarshmallow** [figma/plugin-typings#13]
The document node's id always returns 0:0
and `figma.fileKey` returns undefined. 

I cannot identify the current file running the plugin.

https://www.figma.com/plugin-docs/api/DocumentNode/

[read it on reddit](https://www.reddit.com/r/FigmaDesign/comments/jrd3yd/dev_figma_get_root_document_nodes_id/)

**Comment by cyberalien** [comment]
That's not a bug. `fileKey` is available only in private plug-ins and you need to enable `enablePrivatePluginApi` in manifest.json

Also check out Slack channels for plug-in developers: https://join.slack.com/t/figmaplugins/shared_invite/enQtNjg5NzQ4NTQ4OTAyLWJjOWQyZGRjNmYyZTRmYjk3ZTgzNjJhZTYzZmU5NmJkYzA4MzdjMDFlNzVlM2QwZjhlMGMwMTA5ZWI0N2UxZTA

**Comment by softmarshmallow** [comment]
How about `figma.root.id` ?

**Comment by cyberalien** [comment]
It is always `0:0`. It is not meant to identify document, it is only to reference node within current document.

If you want to identify documents for some reason in your plug-in, best approach is to set plug-in data on root node using `setPluginData`. Then when next time plug-in is ran, that data is available. You can store document specific data that way. If you want multiple plug-ins to access it, use `setSharedPluginData`.

**Comment by softmarshmallow** [comment]
I want to implement a feature that makes sharable link to specific node.

which is figma.com/file/<doc-id>/?node-id=<node-id>

i need the value of `<doc-id>`

**Comment by cyberalien** [comment]
There is no way to get it in plug-in.

**Comment by softmarshmallow** [comment]
Well i think you guys should provide one. Please bring it on the table.
closing for now

**Comment by softmarshmallow** [comment]
@cyberalien Can we get an update / eta for this feature?
I think you can generally agree providing the file id via plugin api is essential.

Use case scenario.
1. Select some node from file
2. If no id provided from plugin, we have to issue new id and manage it customly on app's BE.
3. What happens user moves the node between files? How will we ever access the same node via REST API?

This is very basic feature, must be provided soon.

**Comment by cyberalien** [comment]
> @cyberalien Can we get an update / eta for this feature?

I'm a plugin developer, not part of Figma team.

**Comment by softmarshmallow** [comment]
> > @cyberalien Can we get an update / eta for this feature?
> 
> I'm a plugin developer, not part of Figma team.

Ah. my bad. sorry :)

**Comment by softmarshmallow** [comment]
@delfu

**Comment by delfu** [comment]
@softmarshmallow thank you for trying to develop the best user plugin experience possible :)
Unfortunately there's no plan to provide that capability for non-private plugins because it a plugin security concern. There's been a more detailed discussion on the [plugin slack group](https://figmaplugins.slack.com/archives/CJ37CLHAT/p1602189413004100?thread_ts=1602187668.003400&cid=CJ37CLHAT). 

The summary is exposing file-key can lead to unauthorized access to file content even when a plugin has been uninstalled (eg: plugin gets installed, sends file-key to a server, plugin get uninstalled, the server can still access content through the HTTP API) 

Hope this helps explain the decision

**Comment by zyumbik** [comment]
@delfu I think the suggestion is not necessarily to provide the file key (which would be nice) but to provide any kind of unique identifier for the document. Currently the only option is to send the request to the server which would generate a unique id and store it in node storage, but that won't help if the user resets the document to the previous version before the plugin ran. On the next plugin launch this will be considered a separate doc by the plugin. Currently this is a problem for my plugins as well, for example Master plugin which stores trial usages per file. Technically you can use it infinitely because you can always undo the last action which is stored in the document node plugin storage.
