### ISSUE TITLE
TS Error: 'properties' does not exist on type 'DocumentChange'

### ISSUE THREAD

**Issue by xaviervalarino** [figma/plugin-typings#194]
Been getting this error while subscribing to the `documentchange` event, but I know it's in the docs and in the log.

<img width="973" alt="Screenshot 2023-02-20 at 10 42 25 PM" src="https://user-images.githubusercontent.com/4262486/220267343-bf78a84f-fc57-454d-94d2-67103a6ed58c.png">
<img width="478" alt="Screenshot 2023-02-20 at 10 44 06 PM" src="https://user-images.githubusercontent.com/4262486/220267668-679f371a-9cfe-4f73-aeda-5025d3af344a.png">

I tried:
```
npm rm @figma/plugin-typings
npm i -D @figma/plugin-typings
```
but that didn't do much.

I'm using `node v19.6.0`

**Comment by ymichael** [comment]
Hi @xaviervalarino, I believe the reason typescript is unhappy here is because not all types in `documentChanges` have a "properties" attribute.

Here's more information on all the different types of changes that might appear in e.documentChanges: https://www.figma.com/plugin-docs/api/DocumentChange/

Try this instead:

```
figma.on("documentchange", (e) => {
  for (const change of e.documentChanges) {
    if (change.type === "PROPERTY_CHANGE") {
      const properties = change.properties;
      // DO STUFF
    }
  }
});
```

**Comment by xaviervalarino** [comment]
That fixed it. Thank you very much
