### ISSUE TITLE
Duplicate createVariable

### ISSUE THREAD

**Issue by andreincu** [figma/plugin-typings#288]
At first glance, I thought that `createVariable` is duplicated. However, after a closer look, there is an issue with the definition.

According to docs, the second one should be the valid one (the one with collection property).

<img width="511" alt="image" src="https://github.com/figma/plugin-typings/assets/48840313/9285d2a6-69ca-4d9a-9181-ef8904910827">

**Comment by efrankenbergfigma** [comment]
Hi! Thanks for raising this concern. We actually do maintain typings for both of these versions of `createVariable`, because if users do not migrate their plugins to be Dynamic Page Loading compatible, they can still use the deprecated method that takes in a `collectionId`. There is additional information documenting this release [here](https://www.figma.com/plugin-docs/updates/2024/02/21/version-1-update-87/)!
