### ISSUE TITLE
In ComponentNode constraints field can be undefined

### ISSUE THREAD

**Issue by Miniplop** [figma/plugin-typings#5]
Hello Figma, 

I'm working on a plugin and I notice that **contraints** field can be null for a **ComponentNode**. As the [API documentation ](https://www.figma.com/plugin-docs/api/ComponentNode/#constraints) said : "Constraints of this node relative to its containing FrameNode, if any." So if the component is not in a frame the field doesn't exist in the node.

In the type system, **ComponentNode** extends **DefaultFrameMixin** which is composed by **ConstraintMixin** which defined **constraints** field as always present. I think we have to change this to match this behavior.

What do you think about it ? 

Thank you for your help

**Comment by rudi-c** [comment]
Can you send over a file where a node has null constraint? That shouldn't be possible. Even when a node isn't in a frame, it still retains its constraint value, it just doesn't do anything. You can test this by dragging a node in and out of a frame. Adding `| null` is not desirable if avoidable since it requires the caller to check for null even if that's not applicable most of the time.

**Comment by Miniplop** [comment]
Hello @rudi-c, thank you for your fast answer. I try to reproduce the bug, but I don't manage to do it. I keep you tuned if the bug appear again :)

You can close this issue for now 

Cheers.
